services:
  latentsync:
    build:
      context: .
      dockerfile: Dockerfile
    image: latentsync
    container_name: latentsync
    volumes:
      - .:/app
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true 